Conversation requirements for active and complete quests as well as e…
ProjectSWGCore/Holocore pull request #325
Opened 2021-01-17 20:41 UTC by madsboddum

…vent for granting new quests #315

Fixes #315 

Should enable very basic kill quests to function with credit rewards.

2021-01-17 21:03 UTC, Josh-Larson requested changes
Few things to address - most important is the clientdata loading

2021-01-17 21:03 UTC, Josh-Larson commented on src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java
> +					case "quest.task.ground.comm_player": {
Code clarity wise it may be better to move these into functions, like you did with `completeQuest`

2021-01-17 21:10 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/Quest.java
> +		byte[] completedStepsBytes = Arrays.copyOf(completedTasks.toByteArray(), Short.BYTES);
Yep.

2021-01-17 21:12 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.java
> +		quests.putAll(data.getMap("quests", CRC.class, Quest.class));
It's unused now. Haven't tested, though.

2021-01-17 21:13 UTC, madsboddum commented
> Few things to address - most important is the clientdata loading

Thanks, I'll get on it some time.

2021-01-17 21:13 UTC, Josh-Larson commented on src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.java
> +		quests.putAll(data.getMap("quests", CRC.class, Quest.class));
Good point. If there's nothing to load then there's nothing to break compatibility

2021-02-19 13:44 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
> +		DatatableData datatableData = (DatatableData) ClientFactory.getInfoFromFile(filePath.toFile());
Fixed, still need to do the same for the quest tasks.

2021-02-27 19:58 UTC, merged