Simplified some conditional logic
ProjectSWGCore/Holocore pull request #418
Opened 2022-03-15 16:08 UTC by GeneUNCG

No reason to check if a player's new/old status multiple times in the same statement

2022-03-15 16:33 UTC, Josh-Larson requested changes
Doesn't pass tests (didn't compile) and breaks existing combatant checks

2022-03-15 16:33 UTC, Josh-Larson commented on src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java
> +		if(newStatus == PvpStatus.COMBATANT) {
This doesn't work, in the previous version it was checking two different variables: newStatus and oldStatus

2022-03-16 17:16 UTC, Undercova commented
interestingly now the semicolon appears to be the reason why it fails in the tests
https://github.com/ProjectSWGCore/Holocore/runs/5569563058?check_suite_focus=true

2022-03-16 19:10 UTC, GeneUNCG commented
> interestingly now the semicolon appears to be the reason why it fails in the tests https://github.com/ProjectSWGCore/Holocore/runs/5569563058?check_suite_focus=true

Looked like I was missing one more. It looks to be good now.

2022-03-16 21:53 UTC, Josh-Larson commented
I disagree with the direction of the PR. The previous code was clear in terms of oldStatus -> newStatus, despite duplicating a check.  Generally, if a refactor requires comments to understand the new logic then it shouldn't be done.

2022-03-16 21:53 UTC, closed without merging