Combat level is now a reflection of trained skills instead of accumul…
ProjectSWGCore/Holocore pull request #421
Opened 2022-04-13 11:49 UTC by madsboddum

…ated XP #385

2022-04-13 22:14 UTC, Undercova commented
Working as intended

2022-04-14 17:35 UTC, Josh-Larson requested changes

2022-04-14 17:35 UTC, Josh-Larson commented on src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
> +		boolean levelChanged = !oldCombatLevel.equals(newCombatLevel);
Is this variable necessary?

2022-04-14 17:39 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/PlayerLevelLoader.java
> +		return levels;
Right, it's iterated now over to find the level that has the most fitting xp requirement.

In that way a map made less sense than a collection imo.

2022-04-14 17:40 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
> +			boolean xpTypeAlsoGrantsCombatXp = combatXpMultiplierInfo != null;
I felt a named variable was the best way to convey what the following if-statementbdoes

2022-04-14 17:41 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
> +		boolean levelChanged = !oldCombatLevel.equals(newCombatLevel);
Same as above, it reads better imo

2022-04-14 17:55 UTC, merged