Allow players to get to safety after being incapacitated, to prevent …
ProjectSWGCore/Holocore pull request #427
Opened 2022-04-13 21:12 UTC by madsboddum

…endless incap-revive loop with aggressive NPCs #422

2022-04-13 21:55 UTC, Undercova commented
Working as intended

2022-04-14 17:52 UTC, Josh-Larson requested changes

2022-04-14 17:52 UTC, Josh-Larson commented on src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
> +	private long lastIncapTime;
Can you put this in-line with the other variables, with a default value explicitly set? Even though implicitly it's initialized to zero.

2022-04-14 17:57 UTC, madsboddum commented on src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
> +	private long lastIncapTime;
Good idea, I can change that when I'm near a computer again.

2022-04-17 01:51 UTC, merged